name: Deploy API Hub Infrastructure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # 3. Install Google Cloud SDK (optional but recommended)
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      # 4. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      # 5. Terraform Init
      - name: Terraform Init
        run: terraform init -reconfigure

      # 6. Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve -refresh=true
